version: '3'
services:
  dns:
    image: manfromdownunder/lancachenet-lancache-dns:latest  ## Pulling DNS server for arm
    env_file: .env
    ports:
      - ${DNS_BIND_IP}:53:53/udp
    #volumes:
    #  - /dev/null:/var/log/named/queries.log  #Mount file to dev/null to disable DNS query logging. Comment out to enable BIND logging
    #  - /dev/null:/var/log/named/queries.log.0  #Mount file to dev/null to disable DNS query logging. Comment out to enable BIND logging
    #  - /dev/null:/var/log/named/queries.log.1  #Mount file to dev/null to disable DNS query logging. Comment out to enable BIND logging
    #  - /dev/null:/var/log/named/queries.log.2  #Mount file to dev/null to disable DNS query logging. Comment out to enable BIND logging
    restart: unless-stopped
  monolithic:
    image: manfromdownunder/lancachenet-monolithic:latest ## Pulling monolithic for arm
    env_file: .env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
